CREATE TABLE juego (
	id NUMERIC(10, 0),
	nombre VARCHAR(30),
	descripcion TEXT
) ENGINE=MyISAM,AVG_ROW_LENGTH=0,CHECKSUM=0,DELAY_KEY_WRITE=0,MAX_ROWS=0,MIN_ROWS=0,PACK_KEYS=0;
ALTER TABLE juego ADD CONSTRAINT juego_pk PRIMARY KEY(id);
CREATE TABLE plataforma (
	id NUMERIC(10, 0),
	nombre VARCHAR(20)
) ENGINE=MyISAM,AVG_ROW_LENGTH=0,CHECKSUM=0,DELAY_KEY_WRITE=0,MAX_ROWS=0,MIN_ROWS=0,PACK_KEYS=0;
ALTER TABLE plataforma ADD CONSTRAINT plataforma_pk PRIMARY KEY(id);
CREATE TABLE stock (
	juego NUMERIC(10, 0),
	plataforma NUMERIC(10, 0),
	cantidad NUMERIC(10, 0),
	id NUMERIC(10, 0)
) ENGINE=MyISAM,AVG_ROW_LENGTH=0,CHECKSUM=0,DELAY_KEY_WRITE=0,MAX_ROWS=0,MIN_ROWS=0,PACK_KEYS=0;
ALTER TABLE stock ADD CONSTRAINT stock_pk PRIMARY KEY(id);
CREATE UNIQUE INDEX stock_2 ON stock (plataforma,juego);
CREATE TABLE cliente (
	nombre VARCHAR(30),
	cedula NUMERIC(10, 0),
	telefono NUMERIC(10, 0)
) ENGINE=MyISAM,AVG_ROW_LENGTH=0,CHECKSUM=0,DELAY_KEY_WRITE=0,MAX_ROWS=0,MIN_ROWS=0,PACK_KEYS=0;
ALTER TABLE cliente ADD CONSTRAINT cliente_pk PRIMARY KEY(cedula);
CREATE TABLE reservas (
	juego NUMERIC(10, 0),
	cliente NUMERIC(10, 0)
) ENGINE=MyISAM,AVG_ROW_LENGTH=0,CHECKSUM=0,DELAY_KEY_WRITE=0,MAX_ROWS=0,MIN_ROWS=0,PACK_KEYS=0;
ALTER TABLE reservas ADD CONSTRAINT reservas_pk PRIMARY KEY(juego,cliente);
ALTER TABLE stock ADD CONSTRAINT fk_juego_stock FOREIGN KEY (juego) REFERENCES juego(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE stock ADD CONSTRAINT fe_plataforma_stock FOREIGN KEY (plataforma) REFERENCES plataforma(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE reservas ADD CONSTRAINT fk_stock_reservas FOREIGN KEY (juego) REFERENCES stock(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE reservas ADD CONSTRAINT fk_cliente_reservas FOREIGN KEY (cliente) REFERENCES cliente(cedula) ON DELETE CASCADE ON UPDATE CASCADE;
